### ISSUE TITLE
Error drawing canvas

### ISSUE THREAD

**Issue by vlondon** [coderespawn/dart-color-picker#4]
Class 'CanvasElement' has no instance getter 'context2d'.

NoSuchMethodError : method not found: 'context2d'
Receiver: Instance of 'CanvasElement'
Arguments: []

STACKTRACE:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      HsvGradientPicker.HsvGradientPicker (package:color_picker/widgets/hsv_gradient_picker.dart:61:22)
#2      ColorPicker.ColorPicker (package:color_picker/color_picker_lib.dart:39:18)

**Comment by ghost** [comment]
Exception: Class 'CanvasElement' has no instance getter 'context2d'.

NoSuchMethodError : method not found: 'context2d'
Receiver: Instance of 'CanvasElement'
Arguments: []
  HsvGradientPicker.HsvGradientPicker. (package:color_picker/widgets/hsv_gradient_picker.dart:61:22)
  ColorPicker.ColorPicker. (package:color_picker/color_picker_lib.dart:39:18)

**Comment by lamosty** [comment]
Same error here. Dart version 1.3.0-dev.4.1. This library is not usable.

**Comment by coderespawn** [comment]
It seems to work fine for me. I'm using the latest version

```
Dart Editor version 1.3.3.release (STABLE)
Dart SDK version 1.3.3
```

Could you check with the latest build?

Closing the issue.  If I am missing something, please feel free to reopen it

Thanks

**Comment by mpeterson2** [comment]
Just so you know, you fixed this issue on Github, but you never published it to pub. You may want to do that.

Thanks.

**Comment by coderespawn** [comment]
ah thanks

On Sat, Jun 14, 2014 at 10:00 AM, Michael Peterson <notifications@github.com

**Comment by coderespawn** [comment]
Thanks for the update Michael.  I've bumped up the version to 1.1.4 and
uploaded to pub

Ali
